import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import Navbar from "./component/navbar";
import Sidebar from "./component/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex flex-col justify-center items-center ">
            <div className="w-full h-fit max-w-[1700px] shadow-2xl shadow-stone-400">
              <Navbar />
              <div className="md:flex md:h-fit md:min-w-[1500px] md:-z-10">
                <Sidebar />
                {children}
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
